[27-Aug-2025 00:16:40 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:257
Stack trace:
#0 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/softbbsf/...', 257, 5)
#1 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#2 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#4 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#6 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#8 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(882): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(856): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(831): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(810): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(709): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(597): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 257
[27-Aug-2025 00:17:41 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:257
Stack trace:
#0 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/softbbsf/...', 257, 5)
#1 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#2 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#4 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#6 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#8 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(882): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(856): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(831): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(810): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(709): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(597): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 257
[27-Aug-2025 00:17:45 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:257
Stack trace:
#0 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/softbbsf/...', 257, 5)
#1 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#2 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#4 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#6 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#8 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(882): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(856): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(831): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(810): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(709): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(597): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 257
[27-Aug-2025 00:23:24 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:257
Stack trace:
#0 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/softbbsf/...', 257, 5)
#1 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#2 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#4 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#6 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#8 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(882): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(856): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(831): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(810): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(709): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(597): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 257
[27-Aug-2025 00:23:44 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:257
Stack trace:
#0 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/softbbsf/...', 257, 5)
#1 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#2 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#4 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#6 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#8 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(882): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(856): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(831): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(810): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(709): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(597): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 257
[27-Aug-2025 00:25:06 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\ErrorHandler\ErrorRenderer\highlight_file() in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:257
Stack trace:
#0 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/trace.html.php(36): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->fileExcerpt('/home/softbbsf/...', 257, 5)
#1 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#2 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/traces.html.php(48): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/trace.htm...', Array)
#3 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#4 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception.html.php(54): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/traces.ht...', Array)
#5 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#6 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/Resources/views/exception_full.html.php(35): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#7 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(345): include('/home/softbbsf/...')
#8 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(140): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->include('views/exception...', Array)
#9 /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php(72): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->renderException(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#10 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(882): Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer->render(Object(Symfony\Component\ErrorHandler\Exception\FlattenException))
#11 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(856): Illuminate\Foundation\Exceptions\Handler->renderExceptionWithSymfony(Object(Error), true)
#12 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(831): Illuminate\Foundation\Exceptions\Handler->renderExceptionContent(Object(Error))
#13 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(810): Illuminate\Foundation\Exceptions\Handler->convertExceptionToResponse(Object(Error))
#14 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(709): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Error))
#15 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(597): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error))
#16 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(219): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error))
#17 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(196): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#18 /home/softbbsf/nextalya.softby.net/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#19 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#20 {main}
  thrown in /home/softbbsf/nextalya.softby.net/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php on line 257
